baseurl: "https://sergsoares.github.io"
languageCode: "en-us"
title: "Sergsoares"
theme: "hugo-tania-internal"
paginate: 50
publishDir: "docs"


# disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  # titleEmoji:

  # Logo will show before the blog title on site navbar.
  titleLogo: https://cdn-icons-png.flaticon.com/512/246/246118.png
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: "Sergsoares"
  siteDesc: "Sergsoares"
  author: "Sergsoares"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 50

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to:
    email:
    facebook:
    github:
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram:
    twitter:
    twitch:
    # whatsapp:
  
  # Comments settings
  # comments:
  #   enabled: true
  #   provider: giscus

  #   giscus:
  #     repo: WingLim/hugo-tania
  #     id: MDEwOlJlcG9zaXRvcnkzMTYyNjQzMDc=
  #     category:
  #       name: Comments
  #       id: DIC_kwDOEtnPc84B_WKP

menu:
  # header:
  #   - name: Articles
  #     url: "/articles/"
    # - name: About
    #   url: "/blog/"
  # footer:
  #   - name: RSS
  #     url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
