baseURL = "https://example.com"
title = "SergSoares"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"

[params]
  description = "Blog about automation and IT"
  copyright = "Copyright © 2020 Sergio Soares"
  dark = "auto"
  highlight = true

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
