backend:
  name: git-gateway
  branch: main
media_folder: docs/images
public_folder: /docs
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }